version: '2'
services:
  sqli:
    build: ./sqli
    ports:
      - "7777:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=sqli
      - MYSQL_DATABASE=sqli_db
      - MYSQL_PASSWORD=sqlipassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    expose:
      - "3306"
