version: '2'
services:
  magic1:
    build: ./magic1
    ports:
      - "7331:7331"
  magic2:
    build: ./magic2
    ports:
      - "7332:7332"
  magic3:
    build: ./magic3
    ports:
      - "7333:7333"
    depends_on:
      - db
  magic4:
    build: ./magic4
    ports:
      - "7334:7334"
    depends_on:
      - db2
  magic5:
    build: ./magic5
    ports:
      - "7335:7335"
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=magic3_db
    expose:
      - '5432'
  db2:
    image: mysql:5.7
    environment:
      - MYSQL_USER=magic4
      - MYSQL_DATABASE=magic4_db
      - MYSQL_PASSWORD=magic4password
      - MYSQL_ROOT_PASSWORD=rootpassword
    expose:
      - '3306'